Vagrant.configure(2) do |config|
  config.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible_playbook.yml"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.define "vsrxp1" do |vsrxp1|
    vsrxp1.vm.host_name = "vsrxp1"
    vsrxp1.vm.network "private_network",
                      virtualbox__intnet: "l1"
    vsrxp1.vm.network "private_network",
                      virtualbox__intnet: "l2"
    vsrxp1.vm.network "private_network",
                      virtualbox__intnet: "l3"
  end
  config.vm.define "vsrxp2" do |vsrxp2|
    vsrxp2.vm.host_name = "vsrxp2"
    vsrxp2.vm.network "private_network",
                      virtualbox__intnet: "l1"
    vsrxp2.vm.network "private_network",
                      virtualbox__intnet: "l5"
    vsrxp2.vm.network "private_network",
                      virtualbox__intnet: "l4"
  end
  config.vm.define "vsrxpe3" do |vsrxpe3|
    vsrxpe3.vm.host_name = "vsrxpe3"
    vsrxpe3.vm.network "private_network",
                      virtualbox__intnet: "l6"
    vsrxpe3.vm.network "private_network",
                      virtualbox__intnet: "l2"
    vsrxpe3.vm.network "private_network",
                      virtualbox__intnet: "l4"
  end
  config.vm.define "vsrxpe4" do |vsrxpe4|
    vsrxpe4.vm.host_name = "vsrxpe4"
    vsrxpe4.vm.network "private_network",
                      virtualbox__intnet: "l7"
    vsrxpe4.vm.network "private_network",
                      virtualbox__intnet: "l5"
    vsrxpe4.vm.network "private_network",
                      virtualbox__intnet: "l3"
  end
  config.vm.define "vsrxce5" do |vsrxce5|
    vsrxce5.vm.host_name = "vsrxce5"
    vsrxce5.vm.network "private_network",
                    virtualbox__intnet: "l6"
    vsrxce5.vm.network "private_network",
                    virtualbox__intnet: "l8"
    vsrxce5.vm.network "private_network",
                    virtualbox__intnet: "l9"
  end
  config.vm.define "vsrxce6" do |vsrxce6|
    vsrxce6.vm.host_name = "vsrxce6"
    vsrxce6.vm.network "private_network",
                  virtualbox__intnet: "l7"
    vsrxce6.vm.network "private_network",
                  virtualbox__intnet: "l10"
    vsrxce6.vm.network "private_network",
                  virtualbox__intnet: "l11"
  end
end
